# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS-471 Employee.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_employeeWindow(object):
    def setupUi(self, employeeWindow):
        employeeWindow.setObjectName("employeeWindow")
        employeeWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(employeeWindow)
        self.centralwidget.setObjectName("centralwidget")
        employeeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(employeeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        employeeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(employeeWindow)
        self.statusbar.setObjectName("statusbar")
        employeeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(employeeWindow)
        QtCore.QMetaObject.connectSlotsByName(employeeWindow)

    def retranslateUi(self, employeeWindow):
        _translate = QtCore.QCoreApplication.translate
        employeeWindow.setWindowTitle(_translate("employeeWindow", "Employee View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    employeeWindow = QtWidgets.QMainWindow()
    ui = Ui_employeeWindow()
    ui.setupUi(employeeWindow)
    employeeWindow.show()
    sys.exit(app.exec_())
